### ISSUE TITLE
private method `load' called for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by yourcelf** [unhangout/unhangout-video-server#1]
Tried installing locally using the `./development-environment-init.sh` and ran into trouble.  Could be a vagrant version problem?  I'm running 1.3.4 (latest for my distro); I see that the current latest is 1.7.4.  Here's the output:

```
Running pre-flight checks...
Testing for internet connectivity...
Checking port 2222 for availability...
Checking for Git...
Checking for rsync...
Checking for Vagrant...
Checking for Virtualbox...
All pre-flight checks passed
Initializing development server install...
Creating /home/user/vagrant/example...
Setting up Vagrant configuration for server...
Copying salt config from /home/user/git/unhangout-video-server/vagrant/salt...
sending incremental file list
salt/
salt/minion
            342 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/2)

sent 352 bytes  received 39 bytes  782.00 bytes/sec
total size is 342  speedup is 0.87
Temporarily uninstalling vagrant-vbguest plugin (if necessary)...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Booting server...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Ensuring gcc/make/kernel-devel are installed...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Installing some useful preliminary packages
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Provisioning server...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Running auth.root Salt state...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
Waiting for files to sync to host...
Rebooting server...
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load': private method `load' called for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:98:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/config/loader.rb:95:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:261:in `config_global'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:513:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:28:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:274:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:135:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

Deployment successful.

Add the following entry to your .ssh/config file, then use
'ssh example' to access the installed VM:

Host example
  Hostname localhost
  Port 2222
  User root
  HostKeyAlias example

Note that you must install your hosts's SSH public key on the virtual machine
in order for this to work.
```

The same error gets thrown when I try to use `vm-manage.sh` to issue a vagrant up.

**Comment by thehunmonkgroup** [comment]
guessing your vagrant version is too old, recommend installing the latest 1.7.x for vagrant, and the latest 4.3.x for virtualbox (5.x has a symlinking bug, i've added doc to the README to that effect.)

I've run these scripts successfully on vagrant 1.6.x and 1.7.x, and virtualbox 4.2.x and 4.3.x, YMMV otherwise.
